apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 162154010980-ctgv6ge6jgs4snptv18j8gpsdrean0pv.apps.googleusercontent.co
  MONGODB_URI: <enter-your-mongodb-uri-here>
  NEXTAUTH_URL: <enter-your-nextauth-url-here>
  MONGO_INITDB_ROOT_USERNAME: <enter-your-mongo-username-here>
