apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLW5seVY4cnhvYWVDQ01fbGYycUloa0RoTWlXdTg=
  NEXTAUTH_SECRET: a2b2716dad73843c4d572c43242645873196098c7409b7bd84d4d7172ab8c45b
  NEXT_PUBLIC_API_KEY: QVEuQWI4Uk42Sm9LWnlweXlfZjVNNWdIcXg4NzBCSnNiOU1kSEI1ZFFqUE9uTjhFYVhUOWc=
  MONGO_INITDB_ROOT_PASSWORD: <enter-your-mongo-init-password-here>
